site_name: jaxqualin
site_url: "https://mhycheung.github.io/jaxqualin/"
site_author: Mark Ho-Yeuk Cheung
repo_url: https://github.com/mhycheung/jaxqualin
repo_name: GitHub

theme: material

nav:
  - Home: index.md
  - Examples:
    - Fitting the ringdown: notebooks/example_fit.ipynb
    - Mode search: notebooks/example_mode_selection.ipynb
    - Custom waveform: notebooks/example_custom_waveform.ipynb
    - Loading hyperfits and interpolators: notebooks/example_hyperfit_load.ipynb
  - Results: 
    - 2,2,0 mode: mode_md/2.2.0.md
    - 2,2,1 mode: mode_md/2.2.1.md
    - 2,1,0 mode: mode_md/2.1.0.md
    - 2,1,1 mode: mode_md/2.1.1.md
    - 3,3,0 mode: mode_md/3.3.0.md
    - 3,3,1 mode: mode_md/3.3.1.md
    - 3,2,0 mode: mode_md/3.2.0.md
    - 4,4,0 mode: mode_md/4.4.0.md
    - 5,5,0 mode: mode_md/5.5.0.md
    - r2,2,0 mode: mode_md/-2.2.0.md
    - r2,1,0 mode: mode_md/-2.1.0.md
  - Data: data.md
  - API: 
    - jaxqualin.qnmode: api/qnmode.md
    - jaxqualin.waveforms: api/waveforms.md
    - jaxqualin.fit: api/fit.md
    - jaxqualin.selection: api/selection.md
    - jaxqualin.data: api/data.md

plugins:
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
            show_source: false
            heading_level: 4

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - attr_list
  - md_in_html

extra_javascript:
  - docs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
